# Generated by Django 3.0.5 on 2020-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0002_auto_20200707_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='correo',
            field=models.EmailField(blank=True, max_length=25),
        ),
    ]
