# Generated by Django 3.0.5 on 2020-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0003_auto_20200707_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='adjuntar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registro',
            name='asunto',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='registro',
            name='mensaje',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
